### ISSUE TITLE
實現 WavTokenizer 特徵向量提取與保存功能

### ISSUE THREAD

**Issue by Rita-zi** [Rita-zi/WavTokenizer#1]
## 功能描述
從 WavTokenizer 模型中提取編碼器的輸出特徵向量，並將其保存為文件，以供後續分析使用。

## 技術規格
基於 tsne.py 的實現，需要完成以下功能：

### 核心功能
1. 載入預訓練模型
2. 音頻特徵提取
3. 向量保存

#### 1. 模型初始化
```python
def init_model(config_path, model_path, device):
    model = WavTokenizer.from_pretrained0802(config_path, model_path)
    model.eval()  # 設置為評估模式
    model.to(device)
    return model
```

#### 2. 音頻處理
```python
def process_audio(audio_path, device):
    # 讀取音頻
    wav, sr = torchaudio.load(audio_path)
    if sr != 24000:
        resampler = torchaudio.transforms.Resample(sr, 24000)
        wav = resampler(wav)
    # 正規化
    wav = wav / (torch.max(torch.abs(wav)) + 1e-8)
    return wav.to(device)
```

#### 3. 特徵提取
```python
def extract_features(model, wav):
    with torch.no_grad():
        # 只使用 encoder 部分提取特徵
        features = model.feature_extractor.encodec.encoder(wav)
    return features
```

#### 4. 保存功能
```python
def save_features(features, metadata, save_path):
    os.makedirs(os.path.dirname(save_path), exist_ok=True)
    torch.save({
        'features': features,
        'metadata': metadata
    }, save_path)
```

### 實現步驟

1. 創建新文件 `extract_vectors.py`
2. 實現配置參數管理
3. 實現批次處理邏輯
4. 添加進度顯示
5. 實現保存功能

### 文件結構
```
extract_vectors.py      # 主要實現文件
config/
  └── extract_config.yaml  # 配置文件
output/
  ├── features/           # 特徵向量保存目錄
  └── metadata.json       # 元數據文件
```

### 配置參數
```yaml
model:
  config_path: "./wavtokenizer_mediumdata_frame75_3s_nq1_code4096_dim512_kmeans200_attn.yaml"
  model_path: "./wavtokenizer_large_speech_320_24k.ckpt"

data:
  input_dirs: 
    - "./box"
    - "./plastic"
    - "./papercup"
  batch_size: 16

output:
  save_dir: "./features_output"
  save_format: "pt"  # 可選: pt, npy
```

### 使用示例
```bash
python extract_vectors.py --config config/extract_config.yaml
```

## 注意事項
1. 內存使用效率
   - 使用批次處理
   - 及時釋放不需要的張量

2. 錯誤處理
   - 檢查輸入文件存在性
   - 檢查設備可用性
   - 處理可能的異常

3. 輸出格式
   - 保存完整的特徵向量
   - 包含必要的元數據（檔案名、特徵維度等）

## 驗收標準
1. 能夠正確提取特徵向量
2. 保存格式正確且可重新載入
3. 包含充分的錯誤處理
4. 提供清晰的使用文檔

## 後續工作項目
- [ ] 創建主要實現文件
- [ ] 添加配置文件支持
- [ ] 實現批次處理
- [ ] 添加進度顯示
- [ ] 添加日誌記錄
- [ ] 編寫使用文檔
- [ ] 進行測試和驗證

## 相關文件參考
- tsne.py
- decoder/pretrained.py
